var first_name = prompt("What is your first name?")
var last_name = prompt("What is your last name?")
var age = prompt("What is your age?")
console.log("Great to meet you, "+ first_name + " " + last_name + ".")
console.log("You are "+ age + " years old. Right?")