const isUniform = array => array.every(el => el === array[0])
const sumArray = array => array.reduce((sum, num) => sum + num, 0)
const max = array => Math.max(...array)
const min = array => Math.min(...array)
const sqrt = array => array.map(el => Math.sqrt(el))

console.log(isUniform([1, 1, 1, 1, 1]))
console.log(isUniform([1, 1, 2, 1, 1]))
console.log(sumArray([10, 3, 10, 4]))
console.log(max([-5, 100]))
console.log(min([-5, 100]))
console.log(sqrt([9, 16]))